[2025-05-10T00:51:26.637+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:51:26.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:51:26.642+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:26.641+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:51:26.686+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:26.678+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:51:26.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:51:26.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.096 seconds
[2025-05-10T00:51:57.053+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:51:57.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:51:57.057+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:57.056+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:51:57.116+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:57.105+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:51:57.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:51:57.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.127 seconds
[2025-05-10T00:52:27.912+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:52:27.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:52:27.919+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:27.919+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:52:27.975+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:27.967+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:52:27.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:52:28.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.119 seconds
[2025-05-10T00:52:58.820+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:52:58.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:52:58.826+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:58.826+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:52:58.870+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:58.860+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:52:58.876+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:52:58.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.141 seconds
[2025-05-10T00:53:29.150+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:53:29.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:53:29.155+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:53:29.155+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:53:29.189+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:53:29.183+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:53:29.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:53:29.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.092 seconds
[2025-05-10T00:53:59.941+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:53:59.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:53:59.945+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:53:59.945+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:53:59.980+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:53:59.976+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:53:59.982+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:54:00.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.097 seconds
[2025-05-10T00:54:30.778+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:54:30.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:54:30.781+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:54:30.781+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:54:30.813+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:54:30.807+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:54:30.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:54:30.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.070 seconds
[2025-05-10T00:55:01.638+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:55:01.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:55:01.642+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:01.641+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:55:01.690+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:01.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:55:01.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:55:01.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.089 seconds
[2025-05-10T00:55:32.596+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:55:32.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:55:32.599+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:32.599+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:55:32.629+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:32.623+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:55:32.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:55:32.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.081 seconds
[2025-05-10T00:56:03.302+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:56:03.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:56:03.310+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:03.309+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:56:03.345+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:03.340+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:56:03.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:56:03.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.082 seconds
[2025-05-10T00:56:34.007+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:56:34.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:56:34.014+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:34.013+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:56:34.048+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:34.044+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:56:34.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:56:34.070+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.079 seconds
[2025-05-10T00:57:04.881+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:57:04.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:57:04.885+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:04.885+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:57:04.918+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:04.912+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:57:04.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:57:04.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.069 seconds
[2025-05-10T00:57:35.761+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:57:35.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:57:35.764+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:35.764+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:57:35.794+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:35.789+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:57:35.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:57:35.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.057 seconds
[2025-05-10T00:58:06.471+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:58:06.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:58:06.473+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:06.473+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:58:06.496+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:06.492+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:58:06.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:58:06.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.049 seconds
[2025-05-10T00:58:37.371+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:58:37.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:58:37.375+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:37.374+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:58:37.409+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:37.401+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:58:37.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:58:37.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.067 seconds
[2025-05-10T00:59:08.276+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:59:08.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:59:08.285+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:08.284+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:59:08.335+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:08.327+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:59:08.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:59:08.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.114 seconds
[2025-05-10T00:59:39.096+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:59:39.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T00:59:39.100+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:39.100+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:59:39.143+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:39.137+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
ModuleNotFoundError: No module named 'scripts.dataWarehouse'
[2025-05-10T00:59:39.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T00:59:39.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.077 seconds
[2025-05-10T01:04:23.622+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:04:23.629+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:04:23.634+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:23.633+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:04:23.789+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:23.753+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:04:23.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:04:23.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.246 seconds
[2025-05-10T01:04:54.269+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:04:54.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:04:54.273+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:54.272+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:04:54.334+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:54.323+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:04:54.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:04:54.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.099 seconds
[2025-05-10T01:05:25.279+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:05:25.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:05:25.282+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:25.282+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:05:25.339+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:25.329+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:05:25.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:05:25.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.097 seconds
[2025-05-10T01:05:56.337+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:05:56.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:05:56.341+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:56.340+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:05:56.406+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:56.395+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:05:56.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:05:56.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.104 seconds
[2025-05-10T01:06:27.026+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:06:27.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:06:27.030+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:27.030+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:06:27.080+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:27.068+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:06:27.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:06:27.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.085 seconds
[2025-05-10T01:06:57.664+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:06:57.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:06:57.669+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:57.669+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:06:57.734+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:57.710+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:06:57.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:06:57.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.105 seconds
[2025-05-10T01:08:09.489+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:08:09.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:08:09.495+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:09.494+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:08:09.554+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:09.542+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:08:09.557+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:08:09.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.104 seconds
[2025-05-10T01:08:40.229+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:08:40.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:08:40.233+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:40.232+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:08:40.293+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:40.280+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:08:40.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:08:40.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.129 seconds
[2025-05-10T01:09:11.028+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:09:11.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:09:11.033+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:11.033+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:09:11.097+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:11.084+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:09:11.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:09:11.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.104 seconds
[2025-05-10T01:09:41.750+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:09:41.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:09:41.753+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:41.752+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:09:41.795+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:41.787+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:09:41.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:09:41.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.074 seconds
[2025-05-10T01:10:12.540+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:10:12.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:10:12.543+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:12.543+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:10:12.599+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:12.587+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:10:12.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:10:12.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.086 seconds
[2025-05-10T01:10:43.377+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:10:43.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:10:43.385+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:43.383+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:10:43.480+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:43.465+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:10:43.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:10:43.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.155 seconds
[2025-05-10T01:11:14.237+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:11:14.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:11:14.241+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:14.240+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:11:14.320+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:14.308+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:11:14.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:11:14.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.134 seconds
[2025-05-10T01:11:45.038+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:11:45.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:11:45.047+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:45.046+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:11:45.094+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:45.085+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:11:45.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:11:45.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.095 seconds
[2025-05-10T01:12:15.789+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:12:15.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:12:15.793+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:15.793+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:12:15.849+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:15.834+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:12:15.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:12:15.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.092 seconds
[2025-05-10T01:12:46.667+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:12:46.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:12:46.670+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:46.669+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:12:46.716+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:46.706+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:12:46.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:12:46.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.079 seconds
[2025-05-10T01:13:17.699+0000] {processor.py:161} INFO - Started process (PID=130) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:13:17.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:13:17.705+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:17.705+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:13:17.769+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:17.753+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:13:17.774+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:13:17.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.110 seconds
[2025-05-10T01:13:48.500+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:13:48.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:13:48.503+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:48.503+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:13:48.540+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:48.534+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:13:48.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:13:48.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.075 seconds
[2025-05-10T01:14:19.413+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:14:19.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:14:19.416+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:19.415+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:14:19.621+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:19.580+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_3_warehouse_creator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_3_warehouse_creator.py", line 5, in <module>
    from scripts.dataWarehouse import generate_schema_data_warehouse, load_mssql_tables, load_mysql_tables, load_oracle_tables, load_postgresql_tables, load_sqlite_tables
  File "/opt/airflow/scripts/dataWarehouse.py", line 7, in <module>
    from scripts.tableExtractor import table_extractor_mssql, table_extractor_mysql, table_extractor_oracle, table_extractor_postgresql, table_extractor_sqlite
  File "/opt/airflow/scripts/tableExtractor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:14:19.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:14:19.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.243 seconds
[2025-05-10T01:14:49.723+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:14:49.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:14:49.727+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:49.727+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:14:51.231+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:14:51.308+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:51.308+0000] {override.py:1901} INFO - Created Permission View: can delete on DAG:dag_2_data_ingestor
[2025-05-10T01:14:51.317+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:51.317+0000] {override.py:1901} INFO - Created Permission View: can edit on DAG:dag_2_data_ingestor
[2025-05-10T01:14:51.322+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:51.322+0000] {override.py:1901} INFO - Created Permission View: can read on DAG:dag_2_data_ingestor
[2025-05-10T01:14:51.323+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:51.323+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:14:51.332+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:51.331+0000] {dag.py:3118} INFO - Creating ORM DAG for dag_2_data_ingestor
[2025-05-10T01:14:51.333+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:51.333+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:14:51.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 1.633 seconds
[2025-05-10T01:15:44.153+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:15:44.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:15:44.157+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:44.157+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:15:46.246+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:15:46.353+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:46.352+0000] {override.py:1901} INFO - Created Permission View: can read on DAG:dag_2_data_ingestor
[2025-05-10T01:15:46.365+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:46.365+0000] {override.py:1901} INFO - Created Permission View: can edit on DAG:dag_2_data_ingestor
[2025-05-10T01:15:46.372+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:46.371+0000] {override.py:1901} INFO - Created Permission View: can delete on DAG:dag_2_data_ingestor
[2025-05-10T01:15:46.373+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:46.372+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:15:46.385+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:46.385+0000] {dag.py:3118} INFO - Creating ORM DAG for dag_2_data_ingestor
[2025-05-10T01:15:46.386+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:46.386+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:15:46.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 2.273 seconds
[2025-05-10T01:16:16.822+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:16:16.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:16:16.832+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:16.829+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:16:17.559+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:16:17.599+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:17.599+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:16:17.616+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:17.616+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:16:17.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.836 seconds
[2025-05-10T01:16:48.412+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:16:48.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:16:48.416+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:48.415+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:16:49.040+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:16:49.068+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:49.067+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:16:49.077+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:49.077+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:16:49.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.691 seconds
[2025-05-10T01:17:19.390+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:17:19.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:17:19.399+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:17:19.399+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:17:20.086+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:17:20.111+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:17:20.111+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:17:20.123+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:17:20.123+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:17:20.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.762 seconds
[2025-05-10T01:18:48.154+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:18:48.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:18:48.158+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:48.157+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:18:50.116+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:18:50.135+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:50.134+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:18:50.144+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:50.144+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:18:50.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 2.045 seconds
[2025-05-10T01:19:21.104+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:19:21.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:19:21.107+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:21.106+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:19:21.693+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:19:21.780+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:21.780+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:19:21.790+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:21.789+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:19:21.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.712 seconds
[2025-05-10T01:19:52.697+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:19:52.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:19:52.701+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:52.701+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:19:53.348+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:19:53.370+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:53.369+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:19:53.382+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:53.382+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:19:53.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.747 seconds
[2025-05-10T01:20:23.525+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:20:23.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:20:23.528+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:23.527+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:20:24.098+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:20:24.108+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:24.108+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:20:24.120+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:24.120+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:20:24.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.617 seconds
[2025-05-10T01:20:55.053+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:20:55.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:20:55.059+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:55.059+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:20:55.827+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:20:55.962+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:55.962+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:20:55.972+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:55.971+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:20:55.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.947 seconds
[2025-05-10T01:21:26.973+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:21:26.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:21:26.977+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:26.977+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:21:27.569+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:21:27.596+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:27.595+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:21:27.605+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:27.605+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:21:27.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 0.656 seconds
[2025-05-10T01:21:56.770+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:21:56.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_3_warehouse_creator.py for tasks to queue
[2025-05-10T01:21:56.777+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:56.777+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:21:57.737+0000] {processor.py:840} INFO - DAG(s) 'dag_3_warehouse_creator' retrieved from /opt/airflow/dags/dag_3_warehouse_creator.py
[2025-05-10T01:21:57.864+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:57.862+0000] {override.py:1901} INFO - Created Permission View: can read on DAG:dag_3_warehouse_creator
[2025-05-10T01:21:57.887+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:57.886+0000] {override.py:1901} INFO - Created Permission View: can edit on DAG:dag_3_warehouse_creator
[2025-05-10T01:21:57.902+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:57.901+0000] {override.py:1901} INFO - Created Permission View: can delete on DAG:dag_3_warehouse_creator
[2025-05-10T01:21:57.904+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:57.904+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:21:57.917+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:57.916+0000] {dag.py:3118} INFO - Creating ORM DAG for dag_3_warehouse_creator
[2025-05-10T01:21:57.918+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:57.918+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_3_warehouse_creator to None, run_after=None
[2025-05-10T01:21:57.944+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_3_warehouse_creator.py took 1.186 seconds
