[2025-05-10T00:51:26.794+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:51:26.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:51:26.801+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:26.800+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:51:26.845+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:26.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:51:26.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:51:26.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.107 seconds
[2025-05-10T00:51:57.244+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:51:57.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:51:57.250+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:57.250+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:51:57.294+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:57.289+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:51:57.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:51:57.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.104 seconds
[2025-05-10T00:52:28.079+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:52:28.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:52:28.082+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:28.082+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:52:28.115+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:28.110+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:52:28.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:52:28.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.079 seconds
[2025-05-10T00:52:59.086+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:52:59.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:52:59.096+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:59.095+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:52:59.137+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:59.129+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:52:59.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:52:59.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.095 seconds
[2025-05-10T00:53:29.286+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:53:29.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:53:29.291+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:53:29.291+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:53:29.319+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:53:29.315+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:53:29.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:53:29.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.069 seconds
[2025-05-10T00:54:00.101+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:54:00.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:54:00.103+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:54:00.103+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:54:00.136+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:54:00.129+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:54:00.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:54:00.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.078 seconds
[2025-05-10T00:54:30.908+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:54:30.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:54:30.913+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:54:30.913+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:54:30.978+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:54:30.968+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:54:30.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:54:31.015+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.117 seconds
[2025-05-10T00:55:01.799+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:55:01.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:55:01.803+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:01.803+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:55:01.864+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:01.853+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:55:01.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:55:01.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.116 seconds
[2025-05-10T00:55:32.736+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:55:32.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:55:32.740+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:32.740+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:55:32.768+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:32.763+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:55:32.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:55:32.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.061 seconds
[2025-05-10T00:56:03.425+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:56:03.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:56:03.428+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:03.428+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:56:03.456+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:03.451+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:56:03.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:56:03.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.057 seconds
[2025-05-10T00:56:34.133+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:56:34.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:56:34.136+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:34.136+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:56:34.167+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:34.163+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:56:34.169+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:56:34.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.066 seconds
[2025-05-10T00:57:05.023+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:57:05.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:57:05.026+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:05.025+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:57:05.061+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:05.057+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:57:05.063+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:57:05.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.067 seconds
[2025-05-10T00:57:35.887+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:57:35.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:57:35.891+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:35.890+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:57:35.929+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:35.923+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:57:35.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:57:35.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.077 seconds
[2025-05-10T00:58:06.595+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:58:06.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:58:06.600+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:06.599+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:58:06.637+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:06.632+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:58:06.639+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:58:06.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.072 seconds
[2025-05-10T00:58:37.489+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:58:37.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:58:37.493+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:37.493+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:58:37.525+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:37.521+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:58:37.528+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:58:37.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.064 seconds
[2025-05-10T00:59:08.443+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:59:08.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:59:08.448+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:08.447+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:59:08.479+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:08.474+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:59:08.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:59:08.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.067 seconds
[2025-05-10T00:59:39.226+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:59:39.227+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T00:59:39.229+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:39.229+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:59:39.257+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:39.253+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
ModuleNotFoundError: No module named 'scripts.schemaGenerator'
[2025-05-10T00:59:39.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T00:59:39.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.057 seconds
[2025-05-10T01:04:23.960+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:04:23.962+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:04:23.965+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:23.965+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:04:24.139+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:24.112+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:04:24.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:04:24.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.238 seconds
[2025-05-10T01:04:54.447+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:04:54.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:04:54.452+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:54.452+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:04:54.589+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:54.563+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:04:54.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:04:54.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.181 seconds
[2025-05-10T01:05:25.447+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:05:25.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:05:25.450+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:25.450+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:05:25.503+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:25.491+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:05:25.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:05:25.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.084 seconds
[2025-05-10T01:05:56.521+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:05:56.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:05:56.528+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:56.527+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:05:56.616+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:56.604+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:05:56.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:05:56.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.130 seconds
[2025-05-10T01:06:27.177+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:06:27.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:06:27.180+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:27.180+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:06:27.224+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:27.214+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:06:27.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:06:27.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.075 seconds
[2025-05-10T01:06:57.828+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:06:57.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:06:57.830+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:57.830+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:06:57.872+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:57.863+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:06:57.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:06:57.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.070 seconds
[2025-05-10T01:08:09.676+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:08:09.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:08:09.680+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:09.680+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:08:09.728+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:09.720+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:08:09.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:08:09.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.083 seconds
[2025-05-10T01:08:40.389+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:08:40.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:08:40.393+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:40.393+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:08:40.443+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:40.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:08:40.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:08:40.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.078 seconds
[2025-05-10T01:09:11.196+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:09:11.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:09:11.207+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:11.206+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:09:11.255+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:11.246+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:09:11.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:09:11.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.097 seconds
[2025-05-10T01:09:41.888+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:09:41.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:09:41.891+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:41.891+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:09:41.973+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:41.951+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:09:41.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:09:41.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.115 seconds
[2025-05-10T01:10:12.684+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:10:12.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:10:12.687+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:12.687+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:10:12.758+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:12.750+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:10:12.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:10:12.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.100 seconds
[2025-05-10T01:10:43.594+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:10:43.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:10:43.597+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:43.597+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:10:43.647+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:43.635+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:10:43.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:10:43.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.081 seconds
[2025-05-10T01:11:14.430+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:11:14.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:11:14.434+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:14.433+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:11:14.478+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:14.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:11:14.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:11:14.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.075 seconds
[2025-05-10T01:11:45.174+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:11:45.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:11:45.177+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:45.177+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:11:45.231+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:45.219+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:11:45.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:11:45.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.092 seconds
[2025-05-10T01:12:15.959+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:12:15.962+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:12:15.967+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:15.966+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:12:16.096+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:16.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:12:16.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:12:16.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.174 seconds
[2025-05-10T01:12:46.805+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:12:46.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:12:46.808+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:46.808+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:12:46.854+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:46.845+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:12:46.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:12:46.879+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.083 seconds
[2025-05-10T01:13:17.867+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:13:17.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:13:17.871+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:17.871+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:13:17.925+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:17.916+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:13:17.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:13:17.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.093 seconds
[2025-05-10T01:13:48.651+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:13:48.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:13:48.655+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:48.655+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:13:48.708+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:48.700+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_1_schema_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1_schema_generator.py", line 5, in <module>
    from scripts.schemaGenerator import generate_schema_mssql, generate_schema_mysql, generate_schema_oracle, generate_schema_postgresql, generate_schema_sqlite
  File "/opt/airflow/scripts/schemaGenerator.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:13:48.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:13:48.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.095 seconds
[2025-05-10T01:14:19.691+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:14:19.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:14:19.696+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:19.695+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:14:19.969+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:14:20.066+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:20.065+0000] {override.py:1901} INFO - Created Permission View: can delete on DAG:dag_1_schema_generator
[2025-05-10T01:14:20.075+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:20.075+0000] {override.py:1901} INFO - Created Permission View: can edit on DAG:dag_1_schema_generator
[2025-05-10T01:14:20.081+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:20.081+0000] {override.py:1901} INFO - Created Permission View: can read on DAG:dag_1_schema_generator
[2025-05-10T01:14:20.082+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:20.082+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:14:20.090+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:20.090+0000] {dag.py:3118} INFO - Creating ORM DAG for dag_1_schema_generator
[2025-05-10T01:14:20.092+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:20.092+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:14:20.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.434 seconds
[2025-05-10T01:14:50.902+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:14:50.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:14:50.911+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:50.910+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:14:51.138+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:14:51.183+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:51.183+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:14:51.197+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:51.197+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:14:51.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.328 seconds
[2025-05-10T01:15:44.778+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:15:44.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:15:44.784+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:44.784+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:15:45.103+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:15:45.440+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:45.438+0000] {override.py:1901} INFO - Created Permission View: can read on DAG:dag_1_schema_generator
[2025-05-10T01:15:45.459+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:45.458+0000] {override.py:1901} INFO - Created Permission View: can edit on DAG:dag_1_schema_generator
[2025-05-10T01:15:45.469+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:45.468+0000] {override.py:1901} INFO - Created Permission View: can delete on DAG:dag_1_schema_generator
[2025-05-10T01:15:45.471+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:45.470+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:15:45.488+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:45.487+0000] {dag.py:3118} INFO - Creating ORM DAG for dag_1_schema_generator
[2025-05-10T01:15:45.490+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:45.490+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:15:45.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.757 seconds
[2025-05-10T01:16:16.482+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:16:16.484+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:16:16.487+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:16.486+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:16:16.818+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:16:16.874+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:16.873+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:16:16.888+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:16.888+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:16:16.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.467 seconds
[2025-05-10T01:16:47.164+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:16:47.165+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:16:47.167+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:47.167+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:16:47.398+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:16:47.418+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:47.417+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:16:47.432+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:47.432+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:16:47.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.292 seconds
[2025-05-10T01:17:18.092+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:17:18.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:17:18.095+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:17:18.095+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:17:18.434+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:17:18.464+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:17:18.463+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:17:18.477+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:17:18.477+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:17:18.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.419 seconds
[2025-05-10T01:18:49.106+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:18:49.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:18:49.113+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.112+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:18:49.355+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:18:49.517+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.517+0000] {override.py:1901} INFO - Created Permission View: can read on DAG:dag_1_schema_generator
[2025-05-10T01:18:49.534+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.533+0000] {override.py:1901} INFO - Created Permission View: can edit on DAG:dag_1_schema_generator
[2025-05-10T01:18:49.542+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.541+0000] {override.py:1901} INFO - Created Permission View: can delete on DAG:dag_1_schema_generator
[2025-05-10T01:18:49.543+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.543+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:18:49.554+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.553+0000] {dag.py:3118} INFO - Creating ORM DAG for dag_1_schema_generator
[2025-05-10T01:18:49.555+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.555+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:18:49.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.490 seconds
[2025-05-10T01:19:19.707+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:19:19.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:19:19.710+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:19.710+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:19:19.887+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:19:19.920+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:19.920+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:19:19.935+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:19.935+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:19:19.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.254 seconds
[2025-05-10T01:19:50.297+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:19:50.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:19:50.300+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:50.300+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:19:50.469+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:19:50.492+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:50.492+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:19:50.503+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:50.503+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:19:50.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.238 seconds
[2025-05-10T01:20:21.042+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:20:21.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:20:21.045+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:21.045+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:20:21.228+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:20:21.252+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:21.251+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:20:21.265+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:21.264+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:20:21.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.250 seconds
[2025-05-10T01:20:51.565+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:20:51.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:20:51.568+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:51.568+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:20:51.734+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:20:51.794+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:51.793+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:20:51.821+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:51.821+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:20:51.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.291 seconds
[2025-05-10T01:21:22.476+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:21:22.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:21:22.481+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:22.480+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:21:22.697+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:21:22.727+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:22.727+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:21:22.739+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:22.739+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:21:22.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.299 seconds
[2025-05-10T01:21:53.087+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:21:53.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_1_schema_generator.py for tasks to queue
[2025-05-10T01:21:53.091+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:53.090+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:21:53.271+0000] {processor.py:840} INFO - DAG(s) 'dag_1_schema_generator' retrieved from /opt/airflow/dags/dag_1_schema_generator.py
[2025-05-10T01:21:53.324+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:53.323+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:21:53.338+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:53.338+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_1_schema_generator to None, run_after=None
[2025-05-10T01:21:53.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_1_schema_generator.py took 0.286 seconds
